{
 "title": "Covid-19 NewDataset",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Fields", "query": "SHOW FIELD KEYS" },
   {
    "name": "Country",
    "query": "SHOW TAG VALUES with KEY=countryname"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "content": "<a href=\"http://www.fort-digital.com\" target=\"_blank\"><img src=\"https://www.fort-digital.com/wp-content/uploads/2020/03/FD-FINAL-Dark-BG.png\" height=\"100%\"></a>Corona Data Scraper Project: <a href=\"https://coronadatascraper.com/\" target=\"_blank\">https://github.com/CSSEGISandData/COVID-19</a>\nNB: Data Feeds are constantly changing so expect inconsistencies around Active/Recovered cases whilst this is resolved"
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select last(cases) as time, time as timestamp from covid19",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"cases\") AS \"Cases\", sum(\"deaths\") AS \"Deaths\", sum(\"active\") AS \"Active\", sum(\"recovered\") AS \"Recovered\" FROM \"covid19\" WHERE (\"state\" !~ /./ AND \"county\" !~ /./ AND \"countryname\" =~ /^$Country$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Cases" ], "type": "alias" }
      ],
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "countryname", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"cases\") AS \"Total Cases\" FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total Cases" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"cases\")/sum(\"population\") as \"Population Infected\" FROM \"covid19\" WHERE $timeFilter and \"state\" !~ /./ and (\"countryname\" =~ /^$Country$/) GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"deaths\")/(sum(\"cases\")-sum(\"active\")) as \"Mortality Rate\" FROM \"covid19\" WHERE $timeFilter and  (\"countryname\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT  sum(\"cases\") -  (sum(\"active\") +sum(\"deaths\")) AS \"Recovered\" FROM \"covid19\" WHERE (\"countryname\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1-(sum(\"deaths\")/(sum(\"cases\")-sum(\"active\"))) as \"Recovery Rate\" FROM \"covid19\" WHERE $timeFilter and  (\"countryname\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active Cases" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"cases\") -  (sum(\"active\") +sum(\"deaths\")) AS \"Recovered\" FROM \"covid19\" WHERE (\"countryname\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) AND $timeFilter GROUP BY time(1d), \"geohash\", \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Cases",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"deaths\") FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) AND $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Recovered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT  sum(\"cases\") -  (sum(\"active\") +sum(\"deaths\")) AS \"Recovered\" FROM \"covid19\" WHERE (\"countryname\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) AND $timeFilter GROUP BY time($__interval), \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Cases per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"cases\")/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19\" WHERE $timeFilter and (\"countryname\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) GROUP BY time($__interval), \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Deaths per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT (sum(\"deaths\")/sum(\"population\"))*100000 as \"Population Infected\" FROM \"covid19\" WHERE $timeFilter and (\"countryname\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) GROUP BY time($__interval), \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Recovered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT  non_negative_difference(sum(\"cases\")) -  (non_negative_difference(sum(\"active\")) + non_negative_difference(sum(\"deaths\"))) AS \"Recovered\" FROM \"covid19\" WHERE (\"countryname\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) AND $timeFilter GROUP BY time($__interval), \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "New Cases",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"cases\")) FROM \"covid19\" WHERE (\"countryname\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) AND $timeFilter GROUP BY time($__interval), \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Deaths",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"deaths\")) FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) AND $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Cases per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"cases\"))/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19\" WHERE $timeFilter and (\"countryname\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) GROUP BY time($__interval), \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Deaths per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_countryname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"deaths\"))/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19\" WHERE $timeFilter and (\"countryname\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) GROUP BY time($__interval), \"countryname\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  }
 ]
}