{
 "title": "Covid-19 CDS",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Fields",
    "query": "SHOW FIELD KEYS from \"covid19_CDS\""
   },
   {
    "name": "Country",
    "query": "\tSHOW TAG VALUES from \"covid19_CDS\" with KEY=country"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "content": "<a href=\"http://www.fort-digital.com\" target=\"_blank\"><img src=\"https://www.fort-digital.com/wp-content/uploads/2020/04/FD-FINAL-Dark-BG-e1587590680251.png\" height=\"100%\"></a> Check out our github for more information and to raise issues: <a href=\"https://github.com/FortDigital/covid-19\">https://github.com/FortDigital/covid-19</a>"
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select last(cases) as time, time as timestamp from covid19_CDS where time < now()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "query": "SELECT sum(\"cases\") AS \"Cases\", sum(\"deaths\") AS \"Deaths\", sum(\"active\") AS \"Active\", sum(\"recovered\") AS \"Recovered\" FROM \"covid19\" WHERE (\"state\" !~ /./ AND \"county\" !~ /./ AND \"countryname\" =~ /^$Country$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Cases" ], "type": "alias" }
      ],
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ],
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "query": "SELECT sum(\"cases\") AS \"Total Cases\" FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total Cases" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"cases\")/sum(\"population\") as \"Population Infected\" FROM \"covid19_CDS\" WHERE $timeFilter and \"level\" = 'country' and (\"country\" =~ /^$Country$/) GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"deaths\")/(sum(\"cases\")) as \"Mortality Rate\" FROM \"covid19_CDS\" WHERE $timeFilter and  (\"country\" =~ /^$Country$/ AND \"state\" !~ /./ AND \"county\" !~ /./) GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "query": "SELECT sum(\"recovered\") AS \"Recovered\" FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"level\" = 'country') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "country" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1-(sum(\"deaths\")/sum(\"cases\")) as \"Recovery Rate\" FROM \"covid19_CDS\" WHERE $timeFilter and  (\"country\" =~ /^$Country$/ AND \"level\" ='country') GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active Cases" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "query": "SELECT sum(\"cases\") -  (sum(\"active\") +sum(\"deaths\")) AS \"Recovered\" FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"level\" = 'country') AND $timeFilter GROUP BY time(1d), \"geohash\", \"country\" fill(none)",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "title": "Total Cases",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "query": "SELECT sum(\"deaths\") FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) AND $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "title": "Total Recovered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "query": "SELECT  sum(\"cases\") -  (sum(\"active\") +sum(\"deaths\")) AS \"Recovered\" FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"level\" = 'country') AND $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "title": "Total Cases per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"cases\")/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19_CDS\" WHERE $timeFilter and (\"country\" =~ /^$Country$/ AND \"level\" ='country') GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Deaths per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT (sum(\"deaths\")/sum(\"population\"))*100000 as \"Population Infected\" FROM \"covid19_CDS\" WHERE $timeFilter and (\"country\" =~ /^$Country$/ AND \"level\" = 'country') GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "Total Recovered per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT (sum(\"recovered\")/sum(\"population\"))*100000 as \"Population Infected\" FROM \"covid19_CDS\" WHERE $timeFilter and (\"country\" =~ /^$Country$/ AND \"level\" = 'country') GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Cases",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"cases\")) FROM \"covid19_CDS\" WHERE (\"country\" =~ /^$Country$/  AND \"level\" = 'country') AND $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Deaths",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_CDS",
     "query": "SELECT non_negative_difference(sum(\"deaths\")) FROM \"covid19\" WHERE (\"country\" =~ /^$Country$/ AND \"county\" !~ /./ AND \"state\" !~ /./) AND $timeFilter GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "level", "operator": "=", "value": "country" }
     ]
    }
   ]
  },
  {
   "title": "New Recovered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT  non_negative_difference(sum(\"recovered\")) AS \"Recovered\" FROM \"covid19_CDS\" WHERE (\"country\" =~ /^$Country$/ AND \"level\" = 'country') AND $timeFilter GROUP BY time($__interval), \"country\" fill(0)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "New Cases per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"cases\"))/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19_CDS\" WHERE $timeFilter and (\"country\" =~ /^$Country$/  AND \"level\" = 'country') GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Deaths per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"deaths\"))/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19_CDS\" WHERE $timeFilter and (\"country\" =~ /^$Country$/  AND \"level\" = 'country') GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New Recovered per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"recovered\"))/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19_CDS\" WHERE $timeFilter and (\"country\" =~ /^$Country$/  AND \"level\" = 'country') GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  }
 ]
}