{
 "title": "Covid-19 JHU",
 "description": "Visualisation of Data from John Hopkins University of the Covid-19 Outbreak",
 "time": { "from": "now-60d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "Fields", "query": "confirmed,deaths,recovered" },
   {
    "name": "Country",
    "query": "SHOW TAG VALUES from covid19_JHU with KEY=country"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 0, "y": 0 },
   "content": "<a href=\"http://www.fort-digital.com\" target=\"_blank\"><img src=\"https://www.fort-digital.com/wp-content/uploads/2020/04/FD-FINAL-Dark-BG-e1587590680251.png\" height=\"100%\"></a> Check out our github for more information and to raise issues: <a href=\"https://github.com/FortDigital/covid-19\">https://github.com/FortDigital/covid-19</a>"
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select last(confirmed) as time, time as timestamp from covid19_JHU",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ],
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ],
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Doesnt filter as Population of world hard coded\n\nFuture Improvement to Store Country Populations",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"confirmed\")/sum(\"population\") as \"Population Infected\" FROM \"covid19_JHU\" WHERE $timeFilter and \"country\" =~ /^$Country$/ GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Mortality rate is based on REPORTED cases only and therefore is considerably higher than reality",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"deaths\")/(sum(\"confirmed\")) as \"Mortality Rate\" FROM \"covid19_JHU\" WHERE $timeFilter and \"country\"=~ /$Country/ GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "These are running total's rather than calculating active cases etc.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Mortality rate is based on REPORTED cases only and therefore is considerably higher than reality",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1-sum(\"deaths\")/(sum(\"confirmed\")) as \"Recovery Rate\" FROM \"covid19_JHU\" WHERE $timeFilter and \"country\"=~ /$Country/ GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Confirmed" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Deaths" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Total $Fields",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "repeat": "Fields",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "$Fields" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "Total $Fields per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "repeat": "Fields",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "countryname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT sum(\"$Fields\")/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19_JHU\" WHERE $timeFilter and \"country\" =~ /^$Country$/ GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "countryname", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  {
   "title": "New $Fields",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "repeat": "Fields",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19_JHU",
     "select": [
      [
       { "params": [ "$Fields" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" }
     ]
    }
   ]
  },
  {
   "title": "New $Fields per 100,000",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 33 },
   "repeat": "Fields",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_country",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid19",
     "query": "SELECT non_negative_difference(sum(\"$Fields\"))/sum(\"population\")*100000 as \"Population Infected\" FROM \"covid19_JHU\" WHERE $timeFilter and (\"country\" =~ /^$Country$/) GROUP BY time($__interval), \"country\" fill(none)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$Country$/" },
      { "condition": "AND", "key": "county", "operator": "!~", "value": "/./" },
      { "condition": "AND", "key": "state", "operator": "!~", "value": "/./" }
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 } }
 ]
}